# Final Project Template 

## 2) Provide a link to your data
Your data is required to be free and open to anyone.
As such, you should have a URL which anyone can use to download your data:

Link to Data
- From Kaggle

    https://www.kaggle.com/rtatman/chocolate-bar-ratings

## 3) Import your data
In the space below, import your data.
If your data span multiple files, read them all in.
If applicable, merge or append them as needed.

In [3]:
import pandas as pd
import numpy as np
from pandas import read_csv

In [4]:
Chocolate_df= pd.read_csv('flavors_of_cacao.csv', header=0)

## 4) Show me the head of your data.

In [5]:
#First ten rows of the dataset
Chocolate_df.head(10)

Company \n(Maker-if known) Specific Bean Origin\nor Bar Name   REF  \
0                   A. Morin                       Agua Grande  1876   
1                   A. Morin                             Kpime  1676   
2                   A. Morin                            Atsane  1676   
3                   A. Morin                             Akata  1680   
4                   A. Morin                            Quilla  1704   
5                   A. Morin                          Carenero  1315   
6                   A. Morin                              Cuba  1315   
7                   A. Morin                      Sur del Lago  1315   
8                   A. Morin                    Puerto Cabello  1319   
9                   A. Morin                           Pablino  1319   

   Review\nDate Cocoa\nPercent Company\nLocation  Rating Bean\nType  \
0          2016            63%            France    3.75              
1          2015            70%            France    2.75              
2          2015            70%            France    3.00              
3          2015            70%            France    3.50              
4          2015            70%            France    3.50              
5          2014            70%            France    2.75    Criollo   
6          2014            70%            France    3.50              
7          2014            70%            France    3.50    Criollo   
8          2014            70%            France    3.75    Criollo   
9          2014            70%            France    4.00              

  Broad Bean\nOrigin  
0           Sao Tome  
1               Togo  
2               Togo  
3               Togo  
4               Peru  
5          Venezuela  
6               Cuba  
7          Venezuela  
8          Venezuela  
9               Peru

## 6) Show me the proportion of missing observations for each column of your data

In [6]:
Chocolate_df.isna().head()

Company \n(Maker-if known)  Specific Bean Origin\nor Bar Name    REF  \
0                       False                              False  False   
1                       False                              False  False   
2                       False                              False  False   
3                       False                              False  False   
4                       False                              False  False   

   Review\nDate  Cocoa\nPercent  Company\nLocation  Rating  Bean\nType  \
0         False           False              False   False       False   
1         False           False              False   False       False   
2         False           False              False   False       False   
3         False           False              False   False       False   
4         False           False              False   False       False   

   Broad Bean\nOrigin  
0               False  
1               False  
2               False  
3               False  
4               False

In [7]:
#total NA values in each column
Chocolate_df.isna().sum()

Company \n(Maker-if known)           0
Specific Bean Origin\nor Bar Name    0
REF                                  0
Review\nDate                         0
Cocoa\nPercent                       0
Company\nLocation                    0
Rating                               0
Bean\nType                           1
Broad Bean\nOrigin                   1
dtype: int64

In [8]:
#Where are the NA values
np.where(pd.isnull(Chocolate_df))

(array([1072, 1544]), array([8, 7]))

In [9]:
#Looking at missing values
Chocolate_df.loc[1072,:]

Company \n(Maker-if known)           Mast Brothers
Specific Bean Origin\nor Bar Name       Madagascar
REF                                            999
Review\nDate                                  2012
Cocoa\nPercent                                 72%
Company\nLocation                           U.S.A.
Rating                                         2.5
Bean\nType                              Trinitario
Broad Bean\nOrigin                             NaN
Name: 1072, dtype: object

In [10]:
# But if we look at the data
Chocolate_df.head(10)

Company \n(Maker-if known) Specific Bean Origin\nor Bar Name   REF  \
0                   A. Morin                       Agua Grande  1876   
1                   A. Morin                             Kpime  1676   
2                   A. Morin                            Atsane  1676   
3                   A. Morin                             Akata  1680   
4                   A. Morin                            Quilla  1704   
5                   A. Morin                          Carenero  1315   
6                   A. Morin                              Cuba  1315   
7                   A. Morin                      Sur del Lago  1315   
8                   A. Morin                    Puerto Cabello  1319   
9                   A. Morin                           Pablino  1319   

   Review\nDate Cocoa\nPercent Company\nLocation  Rating Bean\nType  \
0          2016            63%            France    3.75              
1          2015            70%            France    2.75              
2          2015            70%            France    3.00              
3          2015            70%            France    3.50              
4          2015            70%            France    3.50              
5          2014            70%            France    2.75    Criollo   
6          2014            70%            France    3.50              
7          2014            70%            France    3.50    Criollo   
8          2014            70%            France    3.75    Criollo   
9          2014            70%            France    4.00              

  Broad Bean\nOrigin  
0           Sao Tome  
1               Togo  
2               Togo  
3               Togo  
4               Peru  
5          Venezuela  
6               Cuba  
7          Venezuela  
8          Venezuela  
9               Peru

In [11]:
# There are values that are blank which are not counted as NA
#Replace blank cells with NA
ChocolateNa_df = Chocolate_df.replace(r'^\s+$', np.nan, regex=True)

In [12]:
#New total NA values in each column
ChocolateNa_df.isna().sum()

Company \n(Maker-if known)             0
Specific Bean Origin\nor Bar Name      0
REF                                    0
Review\nDate                           0
Cocoa\nPercent                         0
Company\nLocation                      0
Rating                                 0
Bean\nType                           888
Broad Bean\nOrigin                    74
dtype: int64

In [19]:
#Shape showing total number of rows
ChocolateNa_df.shape

(1795, 9)

In [20]:
#Total number of values in each column that are not NA
ChocolateNa_df.count()

Company \n(Maker-if known)           1795
Specific Bean Origin\nor Bar Name    1795
REF                                  1795
Review\nDate                         1795
Cocoa\nPercent                       1795
Company\nLocation                    1795
Rating                               1795
Bean\nType                            907
Broad Bean\nOrigin                   1721
dtype: int64

In [23]:
#Proportion of missing values in each column 
Proportion = (ChocolateNa_df.isna().sum())/(ChocolateNa_df.count()+ChocolateNa_df.isna().sum())
Proportion

Company \n(Maker-if known)           0.000000
Specific Bean Origin\nor Bar Name    0.000000
REF                                  0.000000
Review\nDate                         0.000000
Cocoa\nPercent                       0.000000
Company\nLocation                    0.000000
Rating                               0.000000
Bean\nType                           0.494708
Broad Bean\nOrigin                   0.041226
dtype: float64

# Exploring data and cleaning

In [24]:
#Renaming columns so that there are no more spaces or backslashes
Chocolate= ChocolateNa_df.rename({"Company\xa0\n(Maker-if known)":"Company",
                               'Specific Bean Origin\nor Bar Name': "BeanOrigin",
                              "Review\nDate": "Date",
                              "Cocoa\nPercent": "CocoaPercent",
                                         "Company\nLocation":"Location",
                                         "Bean\nType":"BeanType",
                                         "Broad Bean\nOrigin":"BroadOrigin"}, axis='columns')

In [25]:
Chocolate.head()

Company   BeanOrigin   REF  Date CocoaPercent Location  Rating BeanType  \
0  A. Morin  Agua Grande  1876  2016          63%   France    3.75      NaN   
1  A. Morin        Kpime  1676  2015          70%   France    2.75      NaN   
2  A. Morin       Atsane  1676  2015          70%   France    3.00      NaN   
3  A. Morin        Akata  1680  2015          70%   France    3.50      NaN   
4  A. Morin       Quilla  1704  2015          70%   France    3.50      NaN   

  BroadOrigin  
0    Sao Tome  
1        Togo  
2        Togo  
3        Togo  
4        Peru

In [26]:
#value types
Chocolate.dtypes

Company          object
BeanOrigin       object
REF               int64
Date              int64
CocoaPercent     object
Location         object
Rating          float64
BeanType         object
BroadOrigin      object
dtype: object

In [27]:
# Drop BeanType column because it contains ~ 50% missing values
ChocolateClean=Chocolate.drop(columns=['BeanType'])

In [28]:
ChocolateClean.head()

Company   BeanOrigin   REF  Date CocoaPercent Location  Rating BroadOrigin
0  A. Morin  Agua Grande  1876  2016          63%   France    3.75    Sao Tome
1  A. Morin        Kpime  1676  2015          70%   France    2.75        Togo
2  A. Morin       Atsane  1676  2015          70%   France    3.00        Togo
3  A. Morin        Akata  1680  2015          70%   France    3.50        Togo
4  A. Morin       Quilla  1704  2015          70%   France    3.50        Peru

In [29]:
ChocolateClean.isna().sum()

Company          0
BeanOrigin       0
REF              0
Date             0
CocoaPercent     0
Location         0
Rating           0
BroadOrigin     74
dtype: int64

In [30]:
#There are still NA values in the BroadOrigin column
ChocolateClean.loc[Chocolate.BroadOrigin.isna()].head()

Company     BeanOrigin   REF  Date CocoaPercent   Location  Rating  \
77        Amedei           Nine   111  2007          75%      Italy    4.00   
85        Amedei  Toscano Black   170  2007          63%      Italy    3.50   
86        Amedei  Toscano Black    40  2006          70%      Italy    5.00   
87        Amedei  Toscano Black    75  2006          66%      Italy    4.00   
144  Bahen & Co.     Houseblend  1474  2015          80%  Australia    3.25   

    BroadOrigin  
77          NaN  
85          NaN  
86          NaN  
87          NaN  
144         NaN

In [32]:
#Where are there NA spots
np.where(pd.isnull(ChocolateClean))

(array([  77,   85,   86,   87,  144,  148,  182,  214,  245,  277,  329,
         381,  393,  416,  417,  421,  465,  482,  554,  564,  565,  634,
         644,  739,  749,  754,  755,  756,  759,  760,  762,  764,  769,
         770,  772,  774,  775,  776,  777,  779,  897,  937,  938,  975,
        1048, 1072, 1074, 1114, 1115, 1120, 1129, 1175, 1231, 1272, 1366,
        1374, 1411, 1414, 1436, 1439, 1440, 1443, 1506, 1526, 1624, 1625,
        1683, 1686, 1694, 1766, 1774, 1778, 1780, 1789]),
 array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7]))

In [33]:
#Drop rows with NA values
ChocolateClean2=ChocolateClean.drop([  77,   85,   86,   87,  144,  148,  182,  214,  245,  277,  329,
         381,  393,  416,  417,  421,  465,  482,  554,  564,  565,  634,
         644,  739,  749,  754,  755,  756,  759,  760,  762,  764,  769,
         770,  772,  774,  775,  776,  777,  779,  897,  937,  938,  975,
        1048, 1072, 1074, 1114, 1115, 1120, 1129, 1175, 1231, 1272, 1366,
        1374, 1411, 1414, 1436, 1439, 1440, 1443, 1506, 1526, 1624, 1625,
        1683, 1686, 1694, 1766, 1774, 1778, 1780, 1789])

In [34]:
ChocolateClean2.head()

Company   BeanOrigin   REF  Date CocoaPercent Location  Rating BroadOrigin
0  A. Morin  Agua Grande  1876  2016          63%   France    3.75    Sao Tome
1  A. Morin        Kpime  1676  2015          70%   France    2.75        Togo
2  A. Morin       Atsane  1676  2015          70%   France    3.00        Togo
3  A. Morin        Akata  1680  2015          70%   France    3.50        Togo
4  A. Morin       Quilla  1704  2015          70%   France    3.50        Peru

In [35]:
#Check for NA values
ChocolateClean2.isna().sum()

Company         0
BeanOrigin      0
REF             0
Date            0
CocoaPercent    0
Location        0
Rating          0
BroadOrigin     0
dtype: int64

In [36]:
#Dimensions of cleaned Data
ChocolateClean2.shape

(1721, 8)

In [37]:
#Dimensions of original data
Chocolate_df.shape

(1795, 9)

In [67]:
#Unique ratings
ChocolateClean2.Rating.unique()

array([3.75, 2.75, 3.  , 3.5 , 4.  , 3.25, 2.5 , 5.  , 1.75, 1.5 , 2.25,
       2.  , 1.  ])

In [78]:
#Looking at unique Location
ChocolateClean2.Location.unique()

array(['France', 'U.S.A.', 'Fiji', 'Ecuador', 'Mexico', 'Switzerland',
       'Netherlands', 'Spain', 'Peru', 'Canada', 'Italy', 'Brazil',
       'U.K.', 'Australia', 'Wales', 'Belgium', 'Germany', 'Russia',
       'Puerto Rico', 'Venezuela', 'Colombia', 'Japan', 'New Zealand',
       'Costa Rica', 'South Korea', 'Amsterdam', 'Scotland', 'Martinique',
       'Sao Tome', 'Argentina', 'Guatemala', 'South Africa', 'Bolivia',
       'St. Lucia', 'Portugal', 'Singapore', 'Denmark', 'Vietnam',
       'Grenada', 'Israel', 'India', 'Czech Republic',
       'Domincan Republic', 'Finland', 'Madagascar', 'Philippines',
       'Sweden', 'Poland', 'Austria', 'Honduras', 'Nicaragua',
       'Lithuania', 'Niacragua', 'Chile', 'Ghana', 'Iceland', 'Eucador',
       'Hungary', 'Suriname', 'Ireland'], dtype=object)

In [74]:
#Looking at unique Bean Origins
ChocolateClean2.BeanOrigin.unique()


array(['Agua Grande', 'Kpime', 'Atsane', 'Akata', 'Quilla', 'Carenero',
       'Cuba', 'Sur del Lago', 'Puerto Cabello', 'Pablino', 'Panama',
       'Madagascar', 'Brazil', 'Equateur', 'Colombie', 'Birmanie',
       'Papua New Guinea', 'Chuao', 'Piura', 'Chanchamayo Province',
       'Bolivia', 'Peru', 'Chulucanas, El Platanal', 'Tumbes, Norandino',
       'Vanua Levu', 'Vanua Levu, Toto-A', 'Vanua Levu, Ami-Ami-CA',
       'Los Rios, Quevedo, Arriba', 'Tabasco',
       'Bali (west), Sukrama Family, Melaya area',
       'Madagascar, Ambolikapiky P.', 'Monte Alegre, D. Badero',
       'Trinite', 'Vietnam', 'Piura, Perou', 'Winak Coop, Napo',
       'La Dalia, Matagalpa', 'Tien Giang', 'Makwale Village, Kyela',
       'Momotombo', 'Acopagro', 'CIAAB Coop', 'Villa Andina',
       'Gruppo Salinas', 'Conacado', 'Morobe', 'Dos Rios', 'Guayas',
       'Montanya', 'Bali, Jembrana', 'Cuyagua', 'Ocumare', 'Ghana',
       'Ecuador', 'LamasdelChanka, San Martin, Oro Verde coop',
       'Bellavista

In [75]:
#Looking at number of unique Bean Origins
ChocolateClean2.BeanOrigin.unique().shape

(981,)

In [76]:
ChocolateClean2.CocoaPercent.unique()

array(['63%', '70%', '60%', '80%', '88%', '72%', '55%', '75%', '65%',
       '85%', '73%', '64%', '66%', '68%', '50%', '100%', '77%', '90%',
       '71%', '83%', '78%', '74%', '76%', '86%', '82%', '69%', '91%',
       '42%', '61%', '73.5%', '62%', '67%', '58%', '60.5%', '79%', '81%',
       '57%', '72.5%', '56%', '46%', '89%', '84%', '53%', '87%', '99%'],
      dtype=object)

In [77]:
#Unique values in each column
ChocolateClean2.nunique()

Company         409
BeanOrigin      981
REF             440
Date             12
CocoaPercent     45
Location         60
Rating           13
BroadOrigin      99
dtype: int64

In [79]:
#drop BeanOrigin bc there are so many unique values
ChocolateClean3= ChocolateClean2.drop(columns=['BeanOrigin'])

In [80]:
ChocolateClean3.head()

Company   REF  Date CocoaPercent Location  Rating BroadOrigin
0  A. Morin  1876  2016          63%   France    3.75    Sao Tome
1  A. Morin  1676  2015          70%   France    2.75        Togo
2  A. Morin  1676  2015          70%   France    3.00        Togo
3  A. Morin  1680  2015          70%   France    3.50        Togo
4  A. Morin  1704  2015          70%   France    3.50        Peru

In [81]:
ChocolateClean3.shape

(1721, 7)

In [82]:
#Looking at cocoa percent
ChocolateClean3.CocoaPercent.unique()

array(['63%', '70%', '60%', '80%', '88%', '72%', '55%', '75%', '65%',
       '85%', '73%', '64%', '66%', '68%', '50%', '100%', '77%', '90%',
       '71%', '83%', '78%', '74%', '76%', '86%', '82%', '69%', '91%',
       '42%', '61%', '73.5%', '62%', '67%', '58%', '60.5%', '79%', '81%',
       '57%', '72.5%', '56%', '46%', '89%', '84%', '53%', '87%', '99%'],
      dtype=object)

In [84]:
# Cocoa percent is an object. Remove % sign
ChocolateClean4= ChocolateClean3.replace(r'%', ' ', regex=True)

In [86]:
#CocoaPercent is still an object
ChocolateClean4.dtypes

Company          object
REF               int64
Date              int64
CocoaPercent     object
Location         object
Rating          float64
BroadOrigin      object
dtype: object

In [87]:
#Change to float
Chocolate_cleaned= ChocolateClean4.astype({'CocoaPercent': 'float'})

In [88]:
Chocolate_cleaned.CocoaPercent.unique()

array([ 63. ,  70. ,  60. ,  80. ,  88. ,  72. ,  55. ,  75. ,  65. ,
        85. ,  73. ,  64. ,  66. ,  68. ,  50. , 100. ,  77. ,  90. ,
        71. ,  83. ,  78. ,  74. ,  76. ,  86. ,  82. ,  69. ,  91. ,
        42. ,  61. ,  73.5,  62. ,  67. ,  58. ,  60.5,  79. ,  81. ,
        57. ,  72.5,  56. ,  46. ,  89. ,  84. ,  53. ,  87. ,  99. ])

In [89]:
Chocolate_cleaned.dtypes

Company          object
REF               int64
Date              int64
CocoaPercent    float64
Location         object
Rating          float64
BroadOrigin      object
dtype: object